### PR TITLE
Create Codespace configuration

### PR DESCRIPTION
**Pull request by szlatkow**

### CODE REVIEW

**Comment by aleks-ivanov** [comment]
@szlatkow Does restore work or even it returned errors ?

**Comment by szlatkow** [comment]
@aleks-ivanov  NuGet Restore step is working.

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov ...NuGet Restore step...

@szlatkow this is the Codespace PR, no steps here 🙂 

So if the restore command works, add it to the `postCreateCommands`.

**Review by aleks-ivanov — CHANGES_REQUESTED** [review]
> @aleks-ivanov ...NuGet Restore step...

@szlatkow this is the Codespace PR, no steps here 🙂 

So if the restore command works, add it to the `postCreateCommands`.

**Pull request merged**
